spring:
    servlet:
        multipart:
            max-file-size: 5000000000
            max-request-size: 5000000000
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ${MYSQL_YUBBI_URL}
        username: ${MYSQL_YUBBI_ID}
        password: ${MYSQL_YUBBI_PW}
    jpa:
        database: mysql
        show-sql: true
        hibernate:
            ddl-auto: update
#        defer-datasource-initialization: true

#    sql:
#        init:
#            data-locations: classpath*:db/init.sql
#            mode: always
cloud:
    aws:
        credentials:
            accessKey: ${AWS_ACCESS_KEY}
            secretKey: ${AWS_SECRET_KEY}
        s3:
            bucket: yubbi-contents-bucket
        region:
            static: ap-northeast-2
        stack:
            auto: false
logging:
    level:
        root: info
